### ISSUE TITLE
question about jsonb_init()

### ISSUE THREAD

**Issue by volodimirsmartwave** [lcsmuller/json-build#1]
Hello,

I could not find a better way to ask a question about some implementation details in jsonb_init(), from jason-build.
What is the purpose of the following code:
 void
jsonb_init(jsonb *b)
{
static jsonb empty_builder;
*b = empty_builder;
....

Thanks in advance.
Volodimir

**Comment by lcsmuller** [comment]
Hello, its just a "quick hack" to initialize all of `jsonb` members to zero.

When you create a static or global variable, it is automatically initialized to zero. This:

```c
void
jsonb_init(jsonb *b)
{
  static jsonb empty_builder;
  *b = empty_builder;
...
```
Is analogous to doing
```c

void
jsonb_init(jsonb *b)
{
  b->pos = 0;
  b->top = NULL;
  for (int i = 0; i < JSONB_MAX_DEPTH; ++i)
    b->stack[i] = 0;
...
```
Or
```c
void
jsonb_init(jsonb *b)
{
  memset(b, 0, sizeof(jsonb));
...
```

**Comment by volodimirsmartwave** [comment]
Oh, thanks for answering so quickly. and the next line, *b = empty_builder;?
are copying the empty structure into b?

**Comment by lcsmuller** [comment]
Yup thats precisely whats happening! `empty_builder` has all of its members set to zero, and thats whats being assigned to `*b`

**Comment by volodimirsmartwave** [comment]
I was confused about *b. It is like double pointer because b is already pointer. 
Thanks for the library, i am trying to use it.
By the way, what do you think about moving "jsonb b" inside of the header and adding to it the pointer to the buffer and the length? In this case jsonb_init will become
void
jsonb_init(jsonb *bb, char * ptr, int len)
{
    static jsonb empty_builder;
    *bb = empty_builder;

    bb->top = bb->stack;
    bb->buf_len = len;   // Length of the buffer
    bb->buf_ptr = ptr;  // pointer to the buffer
}

and we could avoid passing the buffer and its length to all the functions?

**Comment by lcsmuller** [comment]
Glad to to hear you are finding some use to it :)

Your suggestion is doable but it can be a little awkward if you need to resize the buffer in case its not large enough, you would need to update the `jsonb` fields everytime that happens. Nevertheless the library should be simple enough for you to wrap your custom logic to it, so you could do something like:

```c
typedef struct myjsonb {
  jsonb builder;
  char *buf;
  size_t bufsize;
} myjsonb;
```
And then,
```c
jsonbcode
myjsonb_push_string(myjsonb *b, 
                    const char str[],
                    size_t len)
{
  return jsonb_push_string(&b->builder, b->buf, b->bufsize, str, len);
}
```

**Comment by volodimirsmartwave** [comment]
Thanks for suggestion. With `myjsonb_push_string` we still pass the buffer and the length to every "push" function. What we initialize the builder with the address of the buffer and its length, and then only pass to the "push" functions the actual needed data?

**Comment by lcsmuller** [comment]
Sorry that was a typo (I fixed it!), it should be passing only the string that will be pushed to the JSON along with its length. buf and bufsize are hidden inside the myjsonb structure.

**Comment by volodimirsmartwave** [comment]
Thanks!

**Comment by lcsmuller** [comment]
No worries, if you got more questions you can open another issue!
