### ISSUE TITLE
possible memory leak when calling _jsonb_escape

### ISSUE THREAD

**Issue by anibalportero** [lcsmuller/json-build#3]
Hi! 

We are using your amazing library and found a potential mem leak. I'm not sure the patch we prepared to solve it is good though:

https://github.com/pantacor/json-build/pull/2

Seems like __jsonb_escape_ was using the complete _bufsize_ but buf was passed as _buf + b->pos_. So could __jsonb_escape_ be writing beyond the limits of _buf_?

To give some context, we are allocating an initial buffer that we resize if any of the build functions return _JSONB_ERROR_NOMEM_.

**Comment by lcsmuller** [comment]
Good catch - I hope I can try your solution later today and then give you a follow-up on it!

Thanks for letting me know, always a great feeling seeing my stuff used by awesome projects.

**Comment by lcsmuller** [comment]
@anibalportero Should be fixed now, thank you for bringing this to my attention!
